package com.deliverysaas.audit;
import java.time.Instant;import java.util.UUID;import org.springframework.data.domain.*;import org.springframework.data.jpa.domain.Specification;import org.springframework.security.core.context.SecurityContextHolder;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.context.request.*;
import com.deliverysaas.audit.domain.AuditLog;import com.deliverysaas.organizations.OrganizationRepository;import com.deliverysaas.organizations.domain.Organization;import com.deliverysaas.shared.security.AuthPrincipal;import com.deliverysaas.users.UserRepository;import com.deliverysaas.users.domain.User;import jakarta.persistence.criteria.Predicate;import jakarta.servlet.http.HttpServletRequest;
@Service public class AuditService{
 private final AuditLogRepository logs;private final UserRepository users;private final OrganizationRepository organizations;public AuditService(AuditLogRepository l,UserRepository u,OrganizationRepository o){logs=l;users=u;organizations=o;}
 public void record(String action,String type,UUID entityId,String description){var authentication=SecurityContextHolder.getContext().getAuthentication();if(authentication==null)return;Object p=authentication.getPrincipal();if(!(p instanceof AuthPrincipal principal))return;record(organizations.getReferenceById(principal.organizationId()),users.getReferenceById(principal.userId()),action,type,entityId,description);}
 public void record(Organization org,User user,String action,String type,UUID entityId,String description){AuditLog log=new AuditLog(org,user,action,type,entityId);log.setDescription(description);log.setIpAddress(clientIp());logs.save(log);}
 @Transactional(readOnly=true) public Page<AuditLogResponse> search(UUID org,UUID user,String action,String type,UUID entity,Instant from,Instant to,Pageable pageable){Specification<AuditLog> spec=(root,q,cb)->{java.util.List<Predicate> p=new java.util.ArrayList<>();p.add(cb.equal(root.get("organization").get("id"),org));if(user!=null)p.add(cb.equal(root.get("user").get("id"),user));if(action!=null&&!action.isBlank())p.add(cb.equal(root.get("action"),action));if(type!=null&&!type.isBlank())p.add(cb.equal(root.get("entityType"),type));if(entity!=null)p.add(cb.equal(root.get("entityId"),entity));if(from!=null)p.add(cb.greaterThanOrEqualTo(root.get("createdAt"),from));if(to!=null)p.add(cb.lessThanOrEqualTo(root.get("createdAt"),to));return cb.and(p.toArray(Predicate[]::new));};return logs.findAll(spec,pageable).map(AuditLogResponse::from);}
 private String clientIp(){RequestAttributes a=RequestContextHolder.getRequestAttributes();return a instanceof ServletRequestAttributes s?s.getRequest().getRemoteAddr():null;}
}
